language: go
go:
 - '1.10'
branches:
  only:
  - master
# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - bin/hugo 

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master 
